services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - CHANGE_TO_COMPOSE_DATA_PATH/portainer:/data
    networks:
      - nginx_proxy_manager
    environment:
      - TZ=${TZ}

networks:
  nginx_proxy_manager:
    external: true
